### ISSUE TITLE
Descriptions are terrible as it is just mashing markdown text together

### ISSUE THREAD

**Issue by dwsmith1983** [dwsmith1983/recommend-resources#13]
We should remove the descriptions or make short descriptions for pages as the current behavior is horrible of mashing markdown text together.

**Comment by beljun** [comment]
I think this can also be closed right? Adding summary metadata overrides the default mashing. 
https://github.com/dwsmith1983/recommend-resources/blob/f66732ed78e19426406574421fad633864e9a437/content/posts/recommendations.md?plain=1#L5
