### ISSUE TITLE
Deployment issue with garden

### ISSUE THREAD

**Issue by dwsmith1983** [dwsmith1983/recommend-resources#4]
@lukkiddd it seems this theme doesn't match with markdown. Is it using a different style?

https://dwsmith1983.github.io/recommend-resources/

**Comment by dwsmith1983** [comment]
Removing the docs folder didn't fix the pages issue.

**Comment by dwsmith1983** [comment]
@lukkiddd I see. The first page mashes everything together. Is there a way to drop this first page or remove the synopsis?

**Comment by lukkiddd** [comment]
Let me take a look
